### ISSUE TITLE
Check existence of files and package descriptors before pushing to tng-cat

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-package#108]
Will allow us to stop early if artifacts `vendor.name.version` are there already.

`curl -H "Content-type:application/json" http://pre-int-sp-ath.5gtango.eu:4011/api/v2/packages?name=asdas&vendor=asdasd&version=0.1`

**Comment by panstav1** [comment]
Highly correlated with this [issue](https://github.com/sonata-nfv/tng-cat/issues/54) of the tng-cat

**Comment by mpeuster** [comment]
see discussion in: https://gitter.im/mpeuster/tng-package-cat-integration
