### ISSUE TITLE
Support 5GTANGO catalogues as storage backend

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-package#14]
- [x] configure catalogue endpoint with ENV variables using the service's docker file (use localhost as fallback, e.g., local dev env)
- [x] upload NAPD.yaml (Attention: ETS-only packages would not work with this backend!)
- [x] upload VNFDs
- [x] upload NSDs
- [x] upload TESTDs
- [x] upload original package file
- [x] upload other arbitrary files to catalogue (e.g. test binaries)
- [x] upload additional catalogue support mapping (endpoint in catalog?, implement in `_build_catalog_metadata`)
    - [x] fix integration bug `(400) File with {name => upb_logo.png, uuid => 2dd10810-d608-45cb-8712-4491df20fbca} not found in the Catalogue`
- [x] return package UUID and send it in callback
- [x] unified upload error handling
- [x] unit tests for storage.py (currently `skip_store=True` in test_unit_rest.py, re-enable!)
- [x] expose skip_store as CLI and ENV config
- [x] test with all three example packages from tng-schema and misc/

Skip all other files in the first prototype.

---

ENV variable naming:

```
 CATALOGUE_URL: http://tng-cat:4011/catalogues/api/v2
```

**Comment by mpeuster** [comment]
Upload order:

0. napd
1. vnfds (if exists)
2. nsds (if exists)
3. testds (if exists)
4. (any other file)
5. package file (*.tgo) = the ZIP
6. additional file mapping to help catalogue


Format of 6.:
```json
"pd" : {
        "vendor" : "eu.sonata-nfv.package",
        "version" : "0.3.1",
        "name" : "sonata-demo"
    },
    "nsds" : [ 
        {
            "vendor" : "eu.sonata-nfv.service-descriptor",
            "version" : "0.2.1",
            "name" : "sonata-demo"
        }
    ],
    "vnfds" : [ 
        {
            "vendor" : "eu.sonata-nfv",
            "version" : "0.3",
            "name" : "firewall-vnf"
        }, 
        {
            "vendor" : "eu.sonata-nfv",
            "version" : "0.2",
            "name" : "iperf-vnf"
        }, 
        {
            "vendor" : "eu.sonata-nfv",
            "version" : "0.2",
            "name" : "tcpdump-vnf"
        }
    ],
    "deps" : [],
    "son_package_uuid" : "78cdd0e2-e3d4-4789-afc7-56269c202b76"
```

**Comment by mpeuster** [comment]
Agreement in call on 2018-04-26:

* v4.0: As described in the comment above. Mostly like SONATA.
* v4.X: Have more generic file storage possibilities.

**Comment by jbonnet** [comment]
Well, @mpeuster, I was counting with the UUID of the package descriptor (which would contain an extra field in its metadata, indicating the package file UUID). Otherwise... how can the descriptor UUID be found?

**Comment by mpeuster** [comment]
Thats the point and also my view. (see the mail that I am about to send out).

**Comment by mpeuster** [comment]
Issue is resolved. See mail.

**Comment by panstav1** [comment]
After the WP3 discussion, below is the updated format of the additional file mapping to help catalogue. The additions are the list of testds trios + a field "files" which includes the file_id, returned from the Catalogue when the individual file is uploaded, and the correspondig filename. @mpeuster  and @jbonnet  what's your view on this?

```
{
	"pd" : {
			"vendor" : "eu.sonata-nfv.package",
			"version" : "0.3.1",
			"name" : "sonata-demo"
		},
	"nsds" : [ 
			{
				"vendor" : "eu.sonata-nfv.service-descriptor",
				"version" : "0.2.1",
				"name" : "sonata-demo"
			}
		],
	"vnfds" : [ 
			{
				"vendor" : "eu.sonata-nfv",
				"version" : "0.3",
				"name" : "firewall-vnf"
			}, 
			{
				"vendor" : "eu.sonata-nfv",
				"version" : "0.2",
				"name" : "iperf-vnf"
			}, 
			{
				"vendor" : "eu.sonata-nfv",
				"version" : "0.2",
				"name" : "tcpdump-vnf"
			}
		],
	"deps" : [],
	"testds" : [
				{
					"name" : "simple-ttcn3-test",
					"vendor" : "eu.5gtango.huawei.simple-test-descriptor",
					"version" : "0.1"
				}
				],
	"files" : [ 
					{ 
						"file_uuid" : "71cdd0e1-d7h9-6641-kgm8-7969c202b76"
						"filename" : "Example.ext"
					}
					],
	"tgo_package_uuid" : "78cdd0e2-e3d4-4789-afc7-56269c202b76"
}
 ```

**Comment by mpeuster** [comment]
Looks ok for me. Just give me the endpoint to send this data, once it is implemented.

Same goes for the endpoint to upload arbitrary files (Example.ext). Once the catalogues support it, I add it to the packager.

**Comment by jbonnet** [comment]
@mpeuster Just a minor-minor thing: `file_name` instead of `filename`? Or `fileuuid` instead of `file_uuid` :)

**Comment by panstav1** [comment]
Updated to file_name :)

**Comment by jbonnet** [comment]
It starts looking great! 👍 
@panstav1 We'll need an example of the response....

**Comment by mpeuster** [comment]
Ok, run in an error when uploading this mapping, the tng-cat returns:

```
File with {name => upb_logo.png, uuid => 7ea6cde0-63cd-4054-a002-b64eb8e0ea91} not found in the Catalogue
```

ecen though a call to `curl -H "Content-type:application/x-yaml" http://localhost:4011/api/catalogues/v2/files` gives:
```
- created_at: '2018-05-04T11:41:27.502+00:00'
  grid_fs_id: 5aec46e791521800010000e4
  grid_fs_name: upb_logo.png
  md5: 6e02d6a13e57d4dc114da4a24961f2ae
  signature:
  updated_at: '2018-05-04T11:41:27.502+00:00'
  username:
  uuid: 7ea6cde0-63cd-4054-a002-b64eb8e0ea91
```

The used mapping is:
```
{"pd": {"vendor": "eu.5gtango", "name": "simple-ttcn3-test", "version": "0.1"}, "nsds": [], "vnfds": [], "testds": [{"vendor": "eu.5gtango.huawei.simple-test-descriptor", "name": "simple-ttcn3-test", "version": "0.1"}], "deps": [], "files": [{"file_uuid": "7ea6cde0-63cd-4054-a002-b64eb8e0ea91", "file_name": "upb_logo.png"}, {"file_uuid": "0de595d2-af6b-4376-ad07-bce53bb64e1a", "file_name": "LICENSE"}, {"file_uuid": "7122c971-dac4-4f8a-8a0c-ac1828a05c21", "file_name": "MyExample"}, {"file_uuid": "53ead82d-824f-4670-8e11-2c483a163980", "file_name": "MyExample.cfg"}, {"file_uuid": "5023475b-1747-4446-b835-5a025a59c2bb", "file_name": "runner.sh"}], "tgo_package_uuid": "2990f855-18c0-4dc2-8455-f055274abf76"}
```

Any ideas?

**Comment by mpeuster** [comment]
Fixed in tng-cat now. This means tng-cat integration is almost done. Needs to be tested a bit more next week.

**Comment by panstav1** [comment]
Firstly, the tng-cat checks the existence of the tgo_package which is mentioned in the mapping file. Then, The mechanism checks for the existence of all files. Now it is fixed. In case of every file being present in the Catalogue, the response is a 200 code with the message "Updated mappings of <tgo_package_uuid>" In case of a file being absent, the tng-cat return a 400 code with a message implying the {name, vendor, version} trio (for descriptors) or {file_name,file_uuid} (for files). So, suppose a VNF descriptor is missing and being referenced in a mapping file, the return would be a 400 code with a message "VNF Descriptor with {name => <name>, vendor => <vendor>, version => <version>} not found in the Catalogue". Also, for files, a 400 code with "File with {name => <file_name>, uuid => <file_uuid>} not found in the Catalogue"
