### ISSUE TITLE
Increase the timer of the package test

### ISSUE THREAD

**Issue by MiguelRivasQuobis** [sonata-nfv/tng-sdk-package#148]
Currently, the validator requires more time to complete the process due to the download of the descriptor schemas, so the time which is used to wait to the packager finalize is not enough in https://github.com/sonata-nfv/tng-sdk-package/blob/f737a1e0d1b2902a168f7e050e85a031f696080b/src/tngsdk/package/tests/test_unit_rest.py#L163 and it produces an error in jenkins pipeline. We tried to increase  the timer to 10 seconds and it is working fine for us.

**Comment by mpeuster** [comment]
Oh really. True could be, it is from pre-validator integration. Let me change it.
