### ISSUE TITLE
Add health check endpoint `/ping` to service mode

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-package#54]
https://git.cs.upb.de/5gtango/UserStories/issues/291

endpoint: `/api/v1/ping`

**Comment by mpeuster** [comment]
We don't have a fixed standard yet. tng-sdk-package will return HTTP status `200` with a body like this:

```json
{
    "ping": "pong",
    "uptime": "b'14:28  up 18 days,  4:32, 13 users, load averages: 2.89 2.90 2.99\\n'"
}

```

**Comment by jbonnet** [comment]
Oh, but we do: just return 200 ok, body is ignored...I wonder if the ed point should be plural, for consistensy...?Em 04/05/2018 13:29, Manuel Peuster <notifications@github.com> escreveu:We don't have a fixed standard yet. tng-sdk-package will return HTTP status 200 with a body like this:
{
    "ping": "pong",
    "uptime": "b'14:28  up 18 days,  4:32, 13 users, load averages: 2.89 2.90 2.99\\n'"
}

**Comment by mpeuster** [comment]
Exactly only 200 in mandatory, body can be anything. This is what I had in my mind. Having the uptime there is fun I think :-)

Plural is also fine with me. Can be easily changed. Just "ping" me ;-)
