### ISSUE TITLE
tng-cat-backend: Replace mapping approach with annotated PD upload

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-package#75]
Lets annotate our package descriptors uploaded to the catalogue so that we do not need the mapping endpoint anymore.

Makes the design mich clearer. (We annotate UUIDs to the files anyhow. )

**Comment by jbonnet** [comment]
Indeed. And these `package_file_id` and `package_file_name` fields could possibly be part of the overall approach to those mappings, instead of a black sheep in a flock of white ones...

**Comment by mpeuster** [comment]
Yes.

In fact these fields are:

```
"package_file_name": "5gtango-ns-package-example.tgo",
 "package_file_uuid": "d26e198c-fdb9-4bdf-ae91-b289605ab838",
```

Full example of a PD: https://gist.github.com/mpeuster/34c6b0d968ce2e079a846e0f903989a0
